# Set the plugin here!
command-mode: console
join-first-time: false
commands-on-close:
- say Hello!
Mode: SimpleForm
title: KygekJoinUI
content: Change in config.yml!
Buttons:
  SimpleForm:
  - name: "Ok"
    image: "textures/ui/confirm"
    commands:
    - "say Hello!"
  ModalForm:
    B1:
      name: Button1
      command: say Button1!
    B2:
      name: Button2
      command: say Button2!


# Whether to check for plugin updates (Recommended)
check-updates: true


##### DANGER ZONE #####
# Do not change this (Only for internal use)!
config-version: 1.5
#######################
...